
export const AgentDummyData: any[] = [
    {
        "id": "AG1",
        "code": "AG001",
        "name": "Thomas Reed",
        "reference": "AGREF201",
        "contactNo": "9867503210",
        "password": "thomasreed123",
        "passwordHash": "agenthashedpassword1",
        "joiningDate": "2023-01-10T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 2,
        "sc": 4,
        "cc": 3,
        "share": 20,
        "mobileShare": 15,
        "icShare": 10,
        "currentLimit": 250,
        "superId": "S1",
        "subId": 300,
        "mcSub": 1,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 15,
        "msSub": 10,
        "icShareSub": 5,
        "reset": true,
        "cshare": 20,
        "cshareSub": 15
    },
    {
        "id": "AG2",
        "code": "AG002",
        "name": "Diana Brooks",
        "reference": "AGREF202",
        "contactNo": "9867503211",
        "password": "dianabrooks123",
        "passwordHash": "agenthashedpassword2",
        "joiningDate": "2023-02-01T00:00:00Z",
        "status": false,
        "casinoCheck": true,
        "mc": 5,
        "sc": 1,
        "cc": 2,
        "share": 25,
        "mobileShare": 20,
        "icShare": 15,
        "currentLimit": 350,
        "superId": "S2",
        "subId": 301,
        "mcSub": 2,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 20,
        "msSub": 15,
        "icShareSub": 10,
        "reset": false,
        "cshare": 25,
        "cshareSub": 20
    },
    {
        "id": "AG3",
        "code": "AG003",
        "name": "Evan Young",
        "reference": "AGREF203",
        "contactNo": "9867503212",
        "password": "evanyoung123",
        "passwordHash": "agenthashedpassword3",
        "joiningDate": "2023-03-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 3,
        "sc": 3,
        "cc": 3,
        "share": 30,
        "mobileShare": 25,
        "icShare": 20,
        "currentLimit": 500,
        "superId": "S3",
        "subId": 302,
        "mcSub": 2,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 25,
        "msSub": 20,
        "icShareSub": 15,
        "reset": true,
        "cshare": 35,
        "cshareSub": 30
    },
    {
        "id": "AG4",
        "code": "AG004",
        "name": "Julia Scott",
        "reference": "AGREF204",
        "contactNo": "9867503213",
        "password": "juliascott123",
        "passwordHash": "agenthashedpassword4",
        "joiningDate": "2023-04-10T00:00:00Z",
        "status": false,
        "casinoCheck": true,
        "mc": 6,
        "sc": 2,
        "cc": 2,
        "share": 35,
        "mobileShare": 30,
        "icShare": 25,
        "currentLimit": 400,
        "superId": "S4",
        "subId": 303,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 28,
        "msSub": 23,
        "icShareSub": 18,
        "reset": false,
        "cshare": 40,
        "cshareSub": 35
    },
    {
        "id": "AG5",
        "code": "AG005",
        "name": "Mark Turner",
        "reference": "AGREF205",
        "contactNo": "9867503214",
        "password": "markturner123",
        "passwordHash": "agenthashedpassword5",
        "joiningDate": "2023-05-01T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 4,
        "sc": 4,
        "cc": 1,
        "share": 40,
        "mobileShare": 35,
        "icShare": 30,
        "currentLimit": 600,
        "superId": "S5",
        "subId": 304,
        "mcSub": 4,
        "scSub": 3,
        "ccSub": 2,
        "shareSub": 33,
        "msSub": 28,
        "icShareSub": 23,
        "reset": true,
        "cshare": 45,
        "cshareSub": 40
    },
    {
        "id": "AG6",
        "code": "AG006",
        "name": "Nora Fisher",
        "reference": "AGREF206",
        "contactNo": "9867503215",
        "password": "norafisher123",
        "passwordHash": "agenthashedpassword6",
        "joiningDate": "2023-05-20T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 2,
        "sc": 5,
        "cc": 2,
        "share": 22,
        "mobileShare": 12,
        "icShare": 7,
        "currentLimit": 450,
        "superId": "S6",
        "subId": 305,
        "mcSub": 1,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 18,
        "msSub": 9,
        "icShareSub": 4,
        "reset": false,
        "cshare": 23,
        "cshareSub": 18
    },
    {
        "id": "AG7",
        "code": "AG007",
        "name": "Carlos Gomez",
        "reference": "AGREF207",
        "contactNo": "9867503216",
        "password": "carlosgomez123",
        "passwordHash": "agenthashedpassword7",
        "joiningDate": "2023-06-01T00:00:00Z",
        "status": false,
        "casinoCheck": false,
        "mc": 3,
        "sc": 3,
        "cc": 4,
        "share": 18,
        "mobileShare": 14,
        "icShare": 9,
        "currentLimit": 300,
        "superId": "S7",
        "subId": 306,
        "mcSub": 2,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 16,
        "msSub": 8,
        "icShareSub": 5,
        "reset": true,
        "cshare": 20,
        "cshareSub": 15
    },
    {
        "id": "A8",
        "code": "AG008",
        "name": "Mia Wilson",
        "reference": "AGREF208",
        "contactNo": "9867503217",
        "password": "miawilson123",
        "passwordHash": "agenthashedpassword8",
        "joiningDate": "2023-06-15T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 1,
        "sc": 6,
        "cc": 3,
        "share": 24,
        "mobileShare": 19,
        "icShare": 14,
        "currentLimit": 500,
        "superId": "S8",
        "subId": 307,
        "mcSub": 1,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 20,
        "msSub": 15,
        "icShareSub": 10,
        "reset": false,
        "cshare": 25,
        "cshareSub": 20
    },
    {
        "id": "AG9",
        "code": "AG009",
        "name": "Lucas Grant",
        "reference": "AGREF209",
        "contactNo": "9867503218",
        "password": "lucasgrant123",
        "passwordHash": "agenthashedpassword9",
        "joiningDate": "2023-07-01T00:00:00Z",
        "status": false,
        "casinoCheck": false,
        "mc": 5,
        "sc": 2,
        "cc": 1,
        "share": 28,
        "mobileShare": 23,
        "icShare": 18,
        "currentLimit": 700,
        "superId": "S9",
        "subId": 308,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 25,
        "msSub": 20,
        "icShareSub": 15,
        "reset": true,
        "cshare": 30,
        "cshareSub": 25
    },
    {
        "id": "AG10",
        "code": "AG010",
        "name": "Isabella Ross",
        "reference": "AGREF210",
        "contactNo": "9867503219",
        "password": "isabellaross123",
        "passwordHash": "agenthashedpassword10",
        "joiningDate": "2023-07-15T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 4,
        "sc": 4,
        "cc": 2,
        "share": 30,
        "mobileShare": 25,
        "icShare": 20,
        "currentLimit": 800,
        "superId": "S10",
        "subId": 309,
        "mcSub": 2,
        "scSub": 3,
        "ccSub": 1,
        "shareSub": 28,
        "msSub": 23,
        "icShareSub": 18,
        "reset": false,
        "cshare": 35,
        "cshareSub": 30
    }
    
];

