import { CancelBets } from "../app/components/games/cancel-bets/cancel-bets.interface";

export const responseData: CancelBets = {
    name: "Admin One",
    code: "dd",
    data: {
      totalPages: 1,
      totalElements: 10,
      size: 25,
      content: [
        {
          sNo: 1,
          code: 2625,
          name: "BENGALURU BLASTERS V GULBARGA MYSTICS",
          dateTime: "2024-08-15 15:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "BENGALURU BLASTERS",
          plusMinus: 0,
        },
        {
          sNo: 2,
          code: 2620,
          name: "TRENT ROCKETS V OVAL INVINCIBLES",
          dateTime: "2024-08-14 23:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "TRENT ROCKETS",
          plusMinus: 0,
        },
        {
          sNo: 3,
          code: 2618,
          name: "SOUTHERN BRAVE V WELSH FIRE",
          dateTime: "2024-08-14 19:30:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "TIE",
          plusMinus: 0,
        },
        {
          sNo: 4,
          code: 2619,
          name: "TRENT ROCKETS WOMEN V OVAL INVINCIBLES WOMEN",
          dateTime: "2024-08-14 19:30:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "OVAL INVINCIBLES WOMEN",
          plusMinus: 0,
        },
        {
          sNo: 5,
          code: 2630,
          name: "MANCHESTER ORIGINALS V NORTHERN SUPERCHARGERS",
          dateTime: "2024-08-13 17:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "MANCHESTER ORIGINALS",
          plusMinus: 0,
        },
        {
          sNo: 6,
          code: 2631,
          name: "LEEDS RHINOS V HULL KR",
          dateTime: "2024-08-13 20:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "LEEDS RHINOS",
          plusMinus: 0,
        },
        {
          sNo: 7,
          code: 2632,
          name: "GLASGOW WARRIORS V EDINBURGH",
          dateTime: "2024-08-12 18:30:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "GLASGOW WARRIORS",
          plusMinus: 0,
        },
        {
          sNo: 8,
          code: 2633,
          name: "EXETER CHIEFS V BATH",
          dateTime: "2024-08-12 16:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "EXETER CHIEFS",
          plusMinus: 0,
        },
        {
          sNo: 9,
          code: 2634,
          name: "LONDON SPIRIT V SOUTHERN BRAVE",
          dateTime: "2024-08-11 14:30:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "LONDON SPIRIT",
          plusMinus: 0,
        },
        {
          sNo: 10,
          code: 2635,
          name: "BIRMINGHAM PHOENIX V TRENT ROCKETS",
          dateTime: "2024-08-11 12:00:00",
          matchType: "T-20",
          declare: "YES",
          wonBy: "BIRMINGHAM PHOENIX",
          plusMinus: 0,
        },
      ],
      number: 0,
      sort: {
        empty: true,
        sorted: false,
        unsorted: true,
      },
      first: true,
      last: true,
      numberOfElements: 10,
      pageable: {
        pageNumber: 0,
        pageSize: 25,
        sort: {
          empty: true,
          sorted: false,
          unsorted: true,
        },
        offset: 0,
        paged: true,
        unpaged: false,
      },
      empty: false,
    },
  };
  