import { ClientDataDetails } from "../app/components/client/client.interface";

export const ClientDummyData: ClientDataDetails[] = [
    {
        "id": "CL1",
        "code": "CL001",
        "name": "Emma Thompson",
        "reference": "CLREF201",
        "contactNo": "9876503210",
        "password": "emmathompson123",
        "passwordHash": "clienthashedpassword1",
        "status": true,
        "casinoCheck": false,
        "mc": 3,
        "sc": 5,
        "cc": 2,
        "share": 15,
        "mobileShare": 10,
        "icShare": 5,
        "currentLimit": 300,
        "agentId": "AG1", 
        "mcSub": 2,
        "scSub": 3,
        "ccSub": 1,
        "shareSub": 13,
        "msSub": 7,
        "icShareSub": 4,
        "reset": true,
        "cshare": 18,
        "cshareSub": 12
    },
    {
        "id": "CL2",
        "code": "CL002",
        "name": "Jack Murphy",
        "reference": "CLREF202",
        "contactNo": "9876503211",
        "password": "jackmurphy123",
        "passwordHash": "clienthashedpassword2",
        "status": false,
        "casinoCheck": true,
        "mc": 2,
        "sc": 1,
        "cc": 3,
        "share": 12,
        "mobileShare": 9,
        "icShare": 6,
        "currentLimit": 250,
        "agentId": "AG2",  // Link to Agent ID
        "mcSub": 1,
        "scSub": 1,
        "ccSub": 2,
        "shareSub": 10,
        "msSub": 5,
        "icShareSub": 3,
        "reset": false,
        "cshare": 15,
        "cshareSub": 10
    },
    {
        "id": "CL3",
        "code": "CL003",
        "name": "Natalie Cole",
        "reference": "CLREF203",
        "contactNo": "9876503212",
        "password": "nataliecole123",
        "passwordHash": "clienthashedpassword3",
        "status": true,
        "casinoCheck": false,
        "mc": 4,
        "sc": 3,
        "cc": 4,
        "share": 20,
        "mobileShare": 15,
        "icShare": 10,
        "currentLimit": 400,
        "agentId": "AG3",  // Link to Agent ID
        "mcSub": 2,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 18,
        "msSub": 12,
        "icShareSub": 8,
        "reset": true,
        "cshare": 22,
        "cshareSub": 17
    },
    {
        "id": "CL4",
        "code": "CL004",
        "name": "Ethan Wright",
        "reference": "CLREF204",
        "contactNo": "9876503213",
        "password": "ethanwright123",
        "passwordHash": "clienthashedpassword4",
        "status": false,
        "casinoCheck": true,
        "mc": 3,
        "sc": 2,
        "cc": 3,
        "share": 25,
        "mobileShare": 20,
        "icShare": 15,
        "currentLimit": 500,
        "agentId": "AG4",  // Link to Agent ID
        "mcSub": 1,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 20,
        "msSub": 15,
        "icShareSub": 10,
        "reset": false,
        "cshare": 30,
        "cshareSub": 25
    },
    {
        "id": "CL5",
        "code": "CL005",
        "name": "Olivia Lee",
        "reference": "CLREF205",
        "contactNo": "9876503214",
        "password": "olivialee123",
        "passwordHash": "clienthashedpassword5",
        "status": true,
        "casinoCheck": false,
        "mc": 5,
        "sc": 4,
        "cc": 1,
        "share": 30,
        "mobileShare": 25,
        "icShare": 20,
        "currentLimit": 300,
        "agentId": "AG5",
        "mcSub": 2,
        "scSub": 3,
        "ccSub": 2,
        "shareSub": 28,
        "msSub": 23,
        "icShareSub": 18,
        "reset": true,
        "cshare": 35,
        "cshareSub": 30
    },
    {
        "id": "CL6",
        "code": "CL006",
        "name": "James Peterson",
        "reference": "CLREF206",
        "contactNo": "9876503215",
        "password": "jamespeterson123",
        "passwordHash": "clienthashedpassword6",
        "status": false,
        "casinoCheck": true,
        "mc": 2,
        "sc": 5,
        "cc": 3,
        "share": 18,
        "mobileShare": 10,
        "icShare": 5,
        "currentLimit": 450,
        "agentId": "AG6",
        "mcSub": 1,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 15,
        "msSub": 10,
        "icShareSub": 7,
        "reset": false,
        "cshare": 20,
        "cshareSub": 15
    }
];
