
export const MasterData:any[]=[
    {
        "id": "M1",
        "code": "MA001",
        "name": "John Doe",
        "reference": "REF123",
        "contactNo": "9876543210",
        "password": "johndoe123",
        "passwordHash": "hashedpassword1",
        "joiningDate": "2022-01-10T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 5,
        "sc": 3,
        "cc": 2,
        "share": 25,
        "mobileShare": 15,
        "icShare": 10,
        "currentLimit": 1000,
        "subAdminId": "SUB1",
        "subId": 100,
        "mcSub": 2,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 20,
        "msSub": 10,
        "icShareSub": 5,
        "reset": false,
        "cshare": 30,
        "cshareSub": 25
    },
    {
        "id": "M2",
        "code": "MA002",
        "name": "Alice Smith",
        "reference": "REF124",
        "contactNo": "9876543211",
        "password": "alicesmith123",
        "passwordHash": "hashedpassword2",
        "joiningDate": "2022-02-15T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 5,
        "sc": 3,
        "cc": 2,
        "share": 30,
        "mobileShare": 20,
        "icShare": 15,
        "currentLimit": 2000,
        "subAdminId": "SUB2",
        "subId": 101,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 25,
        "msSub": 15,
        "icShareSub": 10,
        "reset": true,
        "cshare": 35,
        "cshareSub": 30
    },
    {
        "id": "M3",
        "code": "MA003",
        "name": "Bob Johnson",
        "reference": "REF125",
        "contactNo": "9876543212",
        "password": "bobjohnson123",
        "passwordHash": "hashedpassword3",
        "joiningDate": "2022-03-20T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 5,
        "sc": 3,
        "cc": 2,
        "share": 25,
        "mobileShare": 15,
        "icShare": 10,
        "currentLimit": 1500,
        "subAdminId": "SUB3",
        "subId": 102,
        "mcSub": 2,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 20,
        "msSub": 10,
        "icShareSub": 5,
        "reset": false,
        "cshare": 25,
        "cshareSub": 20
    },
    {
        "id": "M4",
        "code": "MA004",
        "name": "Claire Brown",
        "reference": "REF126",
        "contactNo": "9876543213",
        "password": "clairebrown123",
        "passwordHash": "hashedpassword4",
        "joiningDate": "2022-04-25T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 5,
        "sc": 3,
        "cc": 2,
        "share": 30,
        "mobileShare": 20,
        "icShare": 15,
        "currentLimit": 2000,
        "subAdminId": "SUB4",
        "subId": 103,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 25,
        "msSub": 15,
        "icShareSub": 10,
        "reset": true,
        "cshare": 35,
        "cshareSub": 30
    },
    {
        "id": "M5",
        "code": "MA005",
        "name": "Edward Davis",
        "reference": "REF127",
        "contactNo": "9876543214",
        "password": "edwarddavis123",
        "passwordHash": "hashedpassword5",
        "joiningDate": "2022-05-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 5,
        "sc": 3,
        "cc": 2,
        "share": 20,
        "mobileShare": 10,
        "icShare": 5,
        "currentLimit": 1200,
        "subAdminId": "SUB5",
        "subId": 104,
        "mcSub": 2,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 18,
        "msSub": 8,
        "icShareSub": 4,
        "reset": false,
        "cshare": 22,
        "cshareSub": 18
    },
    // Add more entries (M6, M7, M8, M9, M10) as needed
]
