import { SuperData } from "../app/components/super/super.interface";

export const SuperDummyData:any[] = [
    {
        "id": "S1",
        "code": "SA001",
        "name": "Michael Harris",
        "reference": "REF201",
        "contactNo": "9876503210",
        "password": "michaelharris123",
        "passwordHash": "superhashedpassword1",
        "joiningDate": "2023-01-01T00:00:00Z",
        "status": false,
        "casinoCheck": true,
        "mc": 3,
        "sc": 5,
        "cc": 1,
        "share": 30,
        "mobileShare": 25,
        "icShare": 20,
        "currentLimit": 300,
        "masterId": "M1",
        "subId": 200,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 2,
        "shareSub": 30,
        "msSub": 20,
        "icShareSub": 15,
        "reset": true,
        "cshare": 40,
        "cshareSub": 35
    },
    {
        "id": "S2",
        "code": "SA002",
        "name": "Lisa White",
        "reference": "REF202",
        "contactNo": "9876503211",
        "password": "lisawhite123",
        "passwordHash": "superhashedpassword2",
        "joiningDate": "2023-01-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 4,
        "sc": 2,
        "cc": 3,
        "share": 25,
        "mobileShare": 15,
        "icShare": 10,
        "currentLimit": 100,
        "masterId": "M2",
        "subId": 201,
        "mcSub": 1,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 15,
        "msSub": 10,
        "icShareSub": 5,
        "reset": false,
        "cshare": 25,
        "cshareSub": 20
    },
    {
        "id": "S3",
        "code": "SA003",
        "name": "Kevin Brown",
        "reference": "REF203",
        "contactNo": "9876503212",
        "password": "kevinbrown123",
        "passwordHash": "superhashedpassword3",
        "joiningDate": "2023-02-01T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 6,
        "sc": 4,
        "cc": 2,
        "share": 35,
        "mobileShare": 30,
        "icShare": 25,
        "currentLimit": 200,
        "masterId": "M3",
        "subId": 202,
        "mcSub": 4,
        "scSub": 3,
        "ccSub": 2,
        "shareSub": 33,
        "msSub": 25,
        "icShareSub": 20,
        "reset": true,
        "cshare": 45,
        "cshareSub": 40
    },
    {
        "id": "S4",
        "code": "SA004",
        "name": "Sarah Johnson",
        "reference": "REF204",
        "contactNo": "9876503213",
        "password": "sarahjohnson123",
        "passwordHash": "superhashedpassword4",
        "joiningDate": "2023-02-20T00:00:00Z",
        "status": false,
        "casinoCheck": false,
        "mc": 2,
        "sc": 6,
        "cc": 4,
        "share": 20,
        "mobileShare": 10,
        "icShare": 5,
        "currentLimit": 500,
        "masterId": "M4",
        "subId": 203,
        "mcSub": 2,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 18,
        "msSub": 8,
        "icShareSub": 3,
        "reset": false,
        "cshare": 22,
        "cshareSub": 17
    },
    {
        "id": "S5",
        "code": "SA005",
        "name": "James Miller",
        "reference": "REF205",
        "contactNo": "9876503214",
        "password": "jamesmiller123",
        "passwordHash": "superhashedpassword5",
        "joiningDate": "2023-03-01T00:00:00Z",
        "status": true,
        "casinoCheck": true,
        "mc": 7,
        "sc": 1,
        "cc": 2,
        "share": 40,
        "mobileShare": 35,
        "icShare": 30,
        "currentLimit": 400,
        "masterId": "M5",
        "subId": 204,
        "mcSub": 5,
        "scSub": 3,
        "ccSub": 2,
        "shareSub": 38,
        "msSub": 30,
        "icShareSub": 25,
        "reset": true,
        "cshare": 50,
        "cshareSub": 45
    },
    {
        "id": "S6",
        "code": "SA006",
        "name": "Natalie Wright",
        "reference": "REF206",
        "contactNo": "9876503215",
        "password": "nataliewright123",
        "passwordHash": "superhashedpassword6",
        "joiningDate": "2023-03-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 4,
        "sc": 4,
        "cc": 1,
        "share": 22,
        "mobileShare": 12,
        "icShare": 8,
        "currentLimit": 600,
        "masterId": "M6",
        "subId": 205,
        "mcSub": 1,
        "scSub": 1,
        "ccSub": 1,
        "shareSub": 18,
        "msSub": 9,
        "icShareSub": 4,
        "reset": true,
        "cshare": 28,
        "cshareSub": 23
    },
    {
        "id": "S7",
        "code": "SA007",
        "name": "Oliver Green",
        "reference": "REF207",
        "contactNo": "9876503216",
        "password": "olivergreen123",
        "passwordHash": "superhashedpassword7",
        "joiningDate": "2023-04-01T00:00:00Z",
        "status": false,
        "casinoCheck": true,
        "mc": 6,
        "sc": 2,
        "cc": 3,
        "share": 26,
        "mobileShare": 16,
        "icShare": 11,
        "currentLimit": 500,
        "masterId": "M7",
        "subId": 206,
        "mcSub": 2,
        "scSub": 1,
        "ccSub": 2,
        "shareSub": 20,
        "msSub": 10,
        "icShareSub": 5,
        "reset": false,
        "cshare": 30,
        "cshareSub": 25
    },
    {
        "id": "S8",
        "code": "SA008",
        "name": "Emma Taylor",
        "reference": "REF208",
        "contactNo": "9876503217",
        "password": "emmataylor123",
        "passwordHash": "superhashedpassword8",
        "joiningDate": "2023-04-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 3,
        "sc": 5,
        "cc": 2,
        "share": 28,
        "mobileShare": 18,
        "icShare": 13,
        "currentLimit": 500,
        "masterId": "M8",
        "subId": 207,
        "mcSub": 1,
        "scSub": 2,
        "ccSub": 1,
        "shareSub": 21,
        "msSub": 11,
        "icShareSub": 6,
        "reset": true,
        "cshare": 32,
        "cshareSub": 27
    },
    {
        "id": "S9",
        "code": "SA009",
        "name": "Jacob Moore",
        "reference": "REF209",
        "contactNo": "9876503218",
        "password": "jacobmoore123",
        "passwordHash": "superhashedpassword9",
        "joiningDate": "2023-05-01T00:00:00Z",
        "status": false,
        "casinoCheck": true,
        "mc": 5,
        "sc": 3,
        "cc": 4,
        "share": 24,
        "mobileShare": 14,
        "icShare": 9,
        "currentLimit": 200,
        "masterId": "M9",
        "subId": 208,
        "mcSub": 3,
        "scSub": 2,
        "ccSub": 3,
        "shareSub": 22,
        "msSub": 12,
        "icShareSub": 7,
        "reset": true,
        "cshare": 29,
        "cshareSub": 24
    },
    {
        "id": "S10",
        "code": "SA010",
        "name": "Sophia Lee",
        "reference": "REF210",
        "contactNo": "9876503219",
        "password": "sophialee123",
        "passwordHash": "superhashedpassword10",
        "joiningDate": "2023-05-15T00:00:00Z",
        "status": true,
        "casinoCheck": false,
        "mc": 7,
        "sc": 2,
        "cc": 3,
        "share": 27,
        "mobileShare": 17,
        "icShare": 12,
        "currentLimit": 200,
        "masterId": "M10",
        "subId": 209,
        "mcSub": 4,
        "scSub": 3,
        "ccSub": 2,
        "shareSub": 23,
        "msSub": 13,
        "icShareSub": 8,
        "reset": false,
        "cshare": 31,
        "cshareSub": 26
    }
    
]
